### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Archish007** [Archish007/amazon_clone_tech_task#3]
1) The cart logo in the navigation bar should contain the no. of items in the cart.
2) No. of review given for a product is not shown beside the review star widget, so we can fetch the total no. of review given for a product and display it there.
3) Limit the max lines for description section of product screen and add a see more option

**Comment by mohitrajsinha** [comment]
Hey @Archish007 . I would like to work on this issue. Please assign it to me.

**Comment by Archish007** [comment]
Absolutely, hope you will enjoy contributing to this project. Join our
discord server for more guidance from mentors.
Discord - https://discord.gg/ZjezV3FEV5
