### ISSUE TITLE
User Page

### ISSUE THREAD

**Issue by Archish007** [Archish007/amazon_clone_tech_task#6]
Redesign the UI of the user page to include the options for Profile, Wishlist, and Orders, each of which will redirect to their respective pages.

**Comment by maiHydrogen** [comment]
hey @Archish007 
can i work on this issue?

**Comment by Archish007** [comment]
> hey @Archish007
> can i work on this issue?

Hey! Yes, feel free to go ahead and work on the issue. Reach out to our mentors on our discord channel for any assistance.
Discord- https://discord.gg/ZjezV3FEV5

**Comment by maiHydrogen** [comment]
hey @Archish007 
when i first opened the project on my IDE it prompted me to upgrade my flutter versions and all and hence some build files like gradle,cmake,etc are modified and i lost track of them and now i'm move on started working on the issue so i wanted to know if this okay with this project or i have to revert it back and start over?
and one more thing do i have to build all these requested pages completely or i can build some template and leave or use an existing page like user details for profile (which i personally don't like)?

**Comment by Archish007** [comment]
> hey @Archish007 when i first opened the project on my IDE it prompted me to upgrade my flutter versions and all and hence some build files like gradle,cmake,etc are modified and i lost track of them and now i'm move on started working on the issue so i wanted to know if this okay with this project or i have to revert it back and start over? and one more thing do i have to build all these requested pages completely or i can build some template and leave or use an existing page like user details for profile (which i personally don't like)?

@maiHydrogen upgrade your flutter by running flutter upgrade command in the terminal and then update the dependencies. After that create a new project and fork the repo. If the issue still persist leave a message regarding the issue on our discord server.
             And you don't have to fully build the stated pages just create a blank page for each. The main task is to redesign the ui of user page. You may add new options or features or pages as you like.

**Comment by maiHydrogen** [comment]
@Archish007 
ok got it ! i have made some changes and sharing the screenshots with please tell me anything else is needed.
![Screenshot 2024-10-23 134108](https://github.com/user-attachments/assets/ac27aa20-23a6-495a-b5ea-5dbe921e3adf)
![Screenshot 2024-10-23 134122](https://github.com/user-attachments/assets/c971ae54-7c74-4d8e-b8c8-cf7acc57dac6)
![Screenshot 2024-10-23 134137](https://github.com/user-attachments/assets/01011557-08c8-434e-8963-9e6221a70cc8)
![Screenshot 2024-10-23 134156](https://github.com/user-attachments/assets/a53d06d4-627f-42c0-bbe4-9468b50c429d)
![Screenshot 2024-10-23 134209](https://github.com/user-attachments/assets/a8ac61cd-c025-4cef-9734-40a83c547fd9)

**Comment by Archish007** [comment]
Good work, @maiHydrogen ! However, the current UI is quite basic. Feel free to get more creative and explore platforms like Dribbble for design inspiration.

**Comment by maiHydrogen** [comment]
@Archish007 ok imma try a few designs more and then i'll raise a PR so that you can lookout for any issues.

**Comment by maiHydrogen** [comment]
hey @Archish007 !!
i tried some new designs and come up with one hope you like and if not tell me so[
![Screenshot 2024-10-24 043415](https://github.com/user-attachments/assets/6babe8d8-78d1-4c63-ae9b-91da633bf7c7)
](url)

**Comment by Archish007** [comment]
Hey there, there are slight modifications to the source code. You may either fork the repository again, or simply insert the line after line 33 of the screen_layout page.

**Comment by Archish007** [comment]
@maiHydrogen This UI could use some improvement. Could you please consider redesigning it?

**Comment by maiHydrogen** [comment]
@Archish007 thanks for feedback 
Can you specify what kind of change you want if you have some specific design in your mind or what are things to improve upon generally so that I can keep it in my mind while designing the page ?

**Comment by Archish007** [comment]
@maiHydrogen The current UI looks simplistic, with misaligned cards and gradients that don’t give a professional feel. We need to refine the design by improving alignment, using subtle shadows, consistent padding, and a smoother color scheme to make it more polished like major e-commerce platforms. Try exploring figma and dribble for reference

**Comment by maiHydrogen** [comment]
@Archish007 
i've done a lot of changes to UI and you should have a look on them
![Screenshot 2024-10-25 045316](https://github.com/user-attachments/assets/3f249e82-3215-4ed9-83dd-b42b597fe616)

**Comment by Archish007** [comment]
@maiHydrogen Good work! However, it still needs some adjustments. Please reduce the font size, make the tiles an equal size, and decrease the elevation of the cards..

**Comment by maiHydrogen** [comment]
@Archish007 actually font size is proportional to the tile size, tiles are not of equal size just to avoid old grid style and decreasing elevation will increase darkness of shadows however i can make all these changes but i thought you should know the exact motivation why i designed this . so let me know if you still want the changes.

**Comment by Archish007** [comment]
The current UI has a lot of potential, though it might benefit from a
redesign to enhance its professional appearance.

**Comment by maiHydrogen** [comment]
ok i'll make the changes

**Comment by maiHydrogen** [comment]
@Archish007 which do you like better smaller or bigger ones?
![Screenshot 2024-10-25 174036](https://github.com/user-attachments/assets/4bdc4ed4-d8ca-4dd1-ba3a-7e0fecd78de2)
![Screenshot 2024-10-25 173908](https://github.com/user-attachments/assets/977d9e89-2b6d-4b47-ba0a-3977fa4e8293)

**Comment by Archish007** [comment]
@maiHydrogen send full screenshot for the 2nd one

**Comment by Archish007** [comment]
@maiHydrogen the second one looks decent. Fetch the username from the database and diaplay it in place of user in the hello user tile.

**Comment by Archish007** [comment]
@maiHydrogen also add the sell option in the profile page

**Comment by maiHydrogen** [comment]
@Archish007 i have made changes you asked check this out 
![Screenshot 2024-10-26 075952](https://github.com/user-attachments/assets/7d0d656e-95ba-4263-9338-c24cf21bbb07)
![Screenshot 2024-10-26 080018](https://github.com/user-attachments/assets/6ee0f4a8-3203-4d53-9af0-1f381938ff4d)
![Screenshot 2024-10-26 080036](https://github.com/user-attachments/assets/22da8e90-df78-45c8-868e-adb0a4eed235)

**Comment by Archish007** [comment]
@maiHydrogen Impressive work, but feel free to add more features, animations, or even redesign it to be more creative if you’d like. It’s up to you if you’re not satisfied with this version. If you’re happy with it, I’ll go ahead and merge.

**Comment by maiHydrogen** [comment]
@Archish007 yeah actually there are many small details that has to be more fine tuned and i also wanted to redesign the profile page but as someone else is working on it so i think i'll leave it on them for now i think we could add more options here like payment methods , customer care/ contact us , settings , etc and changing the user icon and button to menu icons and button to avoid confusions among users in the bottom navigation bar. i think i can do the latter stuffs instead of fine tuning them as of now cause i'm being busy with my academic stuff so i can do one final commit within a hour or two (if you want)after that i'm ready to merge it and leave fine tuning things for some other time.

**Comment by Archish007** [comment]
Your interest is greatly appreciated! Feel free to work on those features
at your own pace, as there's still time before the event ends. Take your
time, and happy contributing to open source!

**Comment by Archish007** [comment]
@maiHydrogen You can also work on the profile page. The first contributor with the best quality work will have their PR merged.

**Comment by maiHydrogen** [comment]
@Archish007 I'm done from my  side have a look 
![Screenshot 2024-10-26 155302](https://github.com/user-attachments/assets/47ccff2e-c458-4af7-970b-8c3f310c0fbc)
![Screenshot 2024-10-26 155319](https://github.com/user-attachments/assets/2eefedc4-242d-4c7f-9664-3fe0b81f9458)
for the time being all additional tiles will lead to wishlist page and i've changed gradle to 8.10.2, minSDk version to 34, ndk version and  sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21 from 17 as they were causing build problems on my pc you can reverse them if you experience issues while building.
now you can merge my PR.
thanks for the opportunity

**Comment by maiHydrogen** [comment]
> @maiHydrogen You can also work on the profile page. The first contributor with the best quality work will have their PR merged.

that's nice but that will be rude to the current assignee of the issue cause he will be working hard on this one so let him give a shot after i'll be here anytime.
